<template>
  <aside>
    1：标题、分类、标签、摘要、文章内容、背景图片均为必填项<br>
    2：分类和标签既可以选择已有的也可以随意新增<br>
    3：默认提交的文章状态是草稿，更新博客时不会修改文章状态。想修改发表状态需要到文章列表中去修改<br>
    详情见<a
      href="http://doubj1998.com"
      target="_blank"
    >文档</a>
  </aside>
</template>
